flowchart LR
    Projector --> Aggregate["Aggregate (current state)"]
    style Projector fill:#ff6f00,stroke:#ef6c00,stroke-width:2px
    style Aggregate fill:#880e4f,stroke:#f48fb1,stroke-width:2px

    %% Subgraph styled with Database shape by using a DB-shaped dummy node
    subgraph Database
        Event1
        Event2
        Event3
    end

    Event1 --> Projector
    Event2 --> Projector
    Event3 --> Projector

    style Database fill:#0d47a1,stroke:#0b2d5a,stroke-width:3px
    style Event1 fill:#a5d6a7,stroke:#256029
    style Event2 fill:#a5d6a7,stroke:#256029
    style Event3 fill:#a5d6a7,stroke:#256029
    style Event1 stroke-width:1.5px
    style Event2 stroke-width:1.5px
    style Event3 stroke-width:1.5px
